# Site settings
title: Med Taieb Zorgati Portfolio
email: zorgatitayeb5@gmail.com
url: https://medtaiebz.github.io/portfolio
description: "Showcasing my work in embedded systems, IoT, and hardware design."
keywords: "embedded systems, IoT, hardware design, portfolio, projects"
skills: "Embedded Systems Engineer - IoT Specialist - Hardware Designer"
meta_author: Med Taieb Zorgati

# Google webmaster tools
google_verify:
bing_verify:

# Contact form
contact: static

# Color settings
color:
  primary: 1e90ff
  primary-rgb: "30,144,255"
  secondary: ff4500
  secondary-dark: cd3700

# Footer settings
footer:
  copyright: Med Taieb Zorgati
  location: Sousse, Tunisia
  social: Connect with Me
  credits: 'Portfolio built with Jekyll using the Freelancer theme by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Social networks
social:
  - title: linkedin
    url: http://linkedin.com/in/medtaiebzorgati
  - title: github
    url: http://github.com/medtaiebz

# Address
address:
  - line: Sousse
  - line: Tunisia

# Build settings
markdown: kramdown
permalink: pretty
